package(default_visibility = ["//visibility:public"])

cc_import(
	name = "redis_acl",
	static_library = "lib/libacl_all.a",
	hdrs = glob([
		"include/acl_cpp/**/*.hpp",
		"include/acl_cpp/**/*.ipp",
	])
)



